
export const PROVINCE_NAMES: Record<string, string> = {
  anhui: '安徽',
  beijing: '北京',
  chongqing: '重庆',
  fujian: '福建',
  gansu: '甘肃',
  guangdong: '广东',
  'guangxi-zhuang': '广西',
  guizhou: '贵州',
  hainan: '海南',
  hebei: '河北',
  heilongjiang: '黑龙江',
  henan: '河南',
  'hong-kong': '香港',
  hubei: '湖北',
  hunan: '湖南',
  jiangsu: '江苏',
  jiangxi: '江西',
  jilin: '吉林',
  liaoning: '辽宁',
  macau: '澳门',
  'nei-mongol': '内蒙古',
  'ningxia-hui': '宁夏',
  qinghai: '青海',
  shaanxi: '陕西',
  shandong: '山东',
  shanghai: '上海',
  shanxi: '山西',
  sichuan: '四川',
  tianjin: '天津',
  'xinjiang-uygur': '新疆',
  xizang: '西藏',
  yunnan: '云南',
  zhejiang: '浙江',
  taiwan: '台湾'
};
